# Distributed-Motion-S3 (DMS3) CLIENT configuration file
# TOML 0.4.0

# CheckInterval is the interval (in seconds) for checking the dms server
CheckInterval = 5

# ServerIP is the address on which the dms server is running
ServerIP = "localhost"

# ServerPort is the port on which the dms server is running
ServerPort = 1965

	[logging]
	# LogLevel sets the log levels for application logging using the following table:
	#
	#	0 - OFF, no logging
	#	1 - FATAL, report fatal events
	#	2 - INFO, report informational events
	#  4 - DEBUG, report debugging events
	#
	LogLevel = 4

	# LogDevice determines to what device logging should be set using the following table:
	#
	#	0 - STDOUT (terminal)
	#	1 - log file
	#
	# Ignored if LogLevel == 0
	#
	LogDevice = 1

	# LogFilename is the logging filename
	# Ignored if LogLevel == 0 or LogDevice == 0
	#
	LogFilename = "dms3client.log"

	# LogLocation is the location of logfile (absolute path)
	# Ignored if LogLevel == 0 or LogDevice == 0
	#
	LogLocation = "/var/log"
