# Distributed-Motion-S3 (DMS3) SERVER configuration file
# TOML 0.4.0

# PlayAudio enables (1) or disables (0) the play-back of audio on motion detector application
# start/stop
#
PlayAudio = 1

# ServerPort is the port on which to run the motion server
ServerPort = 1965

# AudioMotionDetectorStart is the audio file played when the motion detector application is
# activated
# By default, the value is "" (empty string), which sets to the path of the local /media folder
# and default file (e.g., /etc/distributed-motion-s3/dms3server/media/motion_start.wav)...
# any other path will be used if valid, else set to local folder
# Ignored if PlayAudio == 0
#
AudioMotionDetectorStart = ""

# AudioMotionDetectorStop is the audio file played when the motion detector application is
# activated
# By default, the value is "" (empty string), which sets to the path of the local /media folder
# and default file (e.g., /etc/distributed-motion-s3/dms3server/media/motion_stop.wav)...
# any other path will be used if valid, else set to local folder
# Ignored if PlayAudio == 0
#
AudioMotionDetectorStop = ""

# ScanForTime enables (true) or disables (false) motion detector application based on time-of-day
ScanForTime = false

# CheckInterval is the interval (in seconds) between checks for change to motion_state
CheckInterval = 15

# AlwaysOnRange is the start and end times (24-hour format) for motion to always be enabled,
# regardless of current IoT device existence on the LAN
# Ignored if ScanForTime == 0
#
AlwaysOnRange = ["2300", "0400"]

# IPBase is the first three address octets defining the LAN (e.g., 10.10.10.) where devices will
# be scanned for to determine when motion should be run
#
IPBase = "10.10.10."

# IPRange is the fourth address octet defined as a range (e.g., 100..254)
IPRange = [100, 254]

# MacsToFind are the MAC addresses of IoT device(s) to search for on the LAN
MacsToFind = ["24:da:9b:0d:53:8f", "f8:cf:c5:d2:bb:9e"]

	[logging]
	# LogLevel sets the log levels for application logging using the following table:
	#
	#  0 - OFF, no logging
	#  1 - FATAL, report fatal events
	#  2 - INFO, report informational events
	#  4 - DEBUG, report debugging events
	#
	LogLevel = 1

	# LogDevice determines to what device logging should be set using the following table:
	#
	#	0 - STDOUT (terminal)
	#	1 - log file
	#
	# Ignored if LogLevel == 0
	#
	LogDevice = 0

	# LogFilename is the logging filename
	# Ignored if LogLevel == 0 or LogDevice == 0
	#
	LogFilename = "dms3server.log"

	# LogLocation is the location of logfile (absolute path)
	# Ignored if LogLevel == 0 or LogDevice == 0
	#
	LogLocation = "/var/log/dms3"
