# Distributed-Motion-S3 (DMS3) CLIENT configuration file
# TOML 0.4.0

[Clients]

   [Clients.0]
      User = "pi"
      DeviceName = "picam-alpha.local"
      SSHPassword = ""        # using SSH certifcate
      RemoteAdminPassword = "PASSWORD"
      Port = "22"
      Platform = 0

   [Clients.1]
      User = "pi"
      DeviceName = "picam-beta.local"
      SSHPassword = ""      # using SSH certifcate
      RemoteAdminPassword = "PASSWORD"
      Port = "22"
      Platform = 0

   [Clients.2]
      User = "richbl"
      DeviceName = "main.local"
      SSHPassword = ""      # using SSH certifcate
      RemoteAdminPassword = "PASSWORD"
      Port = "22"
      Platform = 1

[Servers]

   [Servers.0]
      User = "richbl"
      DeviceName = "main.local"
      SSHPassword = ""      # using SSH certifcate
      RemoteAdminPassword = "PASSWORD"
      Port = "22"
      Platform = 1
